<?php
/**
 * Created by PhpStorm.
 * User: Admin
 * Date: 07.08.2018
 * Time: 17:23
 */

namespace app\models;


use Yii;
use yii\db\ActiveRecord;
use yii\helpers\FileHelper;
use yii\web\UploadedFile;


/**
 * This is the model class for table "history"
 *
 * @property int $id
 * @property string $image_url
 * @property string $description
 *
 **/
class History extends ActiveRecord {

    public $image;
    public $ignoreAfterSave = false;

    public static function tableName() {
        return 'history';
    }

    public function rules() {
        return [
            [['description'], 'required'],
            [['description'], 'string'],
            [['image_url'], 'string', 'max' => 200],
            [['image'], 'safe'],
            [['image'], 'file', 'extensions' => 'jpg, gif, png']
        ];
    }

    public function attributeLabels() {
        return [
            'id'            => 'ID',
            'image_url'     => 'Картинка',
            'image'         => 'Картинка',
            'description'   => 'Описание'
        ];
    }

    public function beforeSave($insert) {

        $path = Yii::$app->basePath . '/web/images/history/';

        if(!file_exists($path))
            FileHelper::createDirectory($path. 0777, true);
            
        $history_image = UploadedFile::getInstance($this, 'image');

        if ($history_image) {
            $files = FileHelper::findFiles($path);

            if ($this->image_url != null) 
            {
                foreach ($files as $file) {
                    if (pathinfo($file, PATHINFO_BASENAME) ==
                        pathinfo($this->image_url, PATHINFO_BASENAME)) {
                        $path_delete_file = Yii::getAlias('@web') . pathinfo($file, PATHINFO_DIRNAME) . '/' .
                            pathinfo($file, PATHINFO_BASENAME);

                        FileHelper::unlink($path_delete_file);
                        break;
                    }
                }
            }

            $this->image_url = '/images/history/' . $history_image->name;
            Yii::$app->params['uploadPath'] = Yii::$app->basePath . '/web';
            $path_to_save = Yii::$app->params['uploadPath'] . $this->image_url;

            $history_image->saveAs($path_to_save);
        }

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

}